#!/bin/sh
#
# This script will build neovim from source and install it to
# ./.build/neovim.
# This script may also be run to update and already built neovim
# installation.

cur_pwd=${PWD}

if [ "$USER" = "root" ]; then
  echo "==> WARN: This should not be run as root."
  exit 2
fi

# TODO: check if make, cmake, git and ninja are
# installed

# cd to the parent directory of this script
cd "$(dirname "$0")"
scripts=$PWD
# cd to the root of the project
cd ../

if [ ! -d "./.build/neovim" ]; then
  echo "==> ./.build/neovim does not exist, cloning ..."
  sleep 1
  git clone --depth 1 https://github.com/neovim/neovim ./.build/neovim
fi
cd ./.build/neovim
echo "==> fetching origin tags/nightly ..."
echo
sleep 1
git fetch --depth=1 origin +refs/tags/nightly:refs/tags/nightly
git checkout tags/nightly

echo
echo "==> Cleaning old build ..."
sleep 2

# If build and .deps directories exist, remove them
# so the build is clean
if [ -d "./build" ]; then
  echo "==> Removing old build directory..."
  rm -rf ./build
fi
if [ -d "./.deps" ]; then
  echo "==> Removing old dependencies directory ..."
  rm -rf ./.deps
fi

echo
echo "==> Starting a new build ..."
echo
sleep 2
# Build neovim insto a custom directory
# And ensure to build in release mode, so it is fast
# and does not include debug logs
make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=${PWD}/build" CMAKE_BUILD_TYPE=Release install

echo
echo "==> Build complete. (run '${scripts}/build' to update neovim)"

cd ${cur_pwd}
