#!/bin/sh

if [ "$USER" != "root" ]
then
    echo "==> ERROR: Can only be run as root, exiting."
    exit 2
fi

cd "$(dirname "$0")"
cd ../

nvim_link=$(readlink -f ${HOME}/.config/nvim)
if [ "$nvim_link" = "${PWD}/.config/nvim" ]; then
    echo "==> unlinking nvim config from ~/.config/nvim"
    rm ${HOME}/.config/nvim
fi

# link ./kitty to ~/.config/kitty
kitty_link=$(readlink -f ${HOME}/.config/kitty)
if [ "$kitty_link" = "${PWD}/.config/kitty" ]; then
    echo "==> unlinking kitty config from ~/.config/nvim"
    rm ${HOME}/.config/kitty
fi

# link ./kitty to ~/.config/kitty
nvim_build_link=$(readlink -f /usr/bin/nvim)
if [ "$nvim_build_link" = "${PWD}/.build/neovim/build/bin/nvim" ]; then
    read -p "==? Unlink neovim build? [y/n] " -n 1 -r
    echo    # (optional) move to a new line
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
        echo "==> unlinking nvim binary from /usr/bin/nvim"
        rm /usr/bin/nvim
    fi
fi
