#!/bin/sh

if [ "$USER" = "root" ]
then
    echo "==> WARN: This should not be run as root."
    exit 2
fi

cd "$(dirname "$0")"
cd ../

read -p "==? Build/Update neovim from source? [y/n] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo "==> building neovim"
    ./scripts/build/nvim
fi

# link neovim config only when nvim available
if command -v nvim &> /dev/null
then
    nvim_link=$(readlink -f $HOME/.config/nvim)
    if [ "$nvim_link" = "${PWD}/.config/nvim" ]; then
    	echo "==> neovim config link to ~/.config/nvim already exists"
    else
    	echo "==> linking  neovim config to ~/.config/nvim"
        ln -s ${PWD}/.config/nvim $HOME/.config/nvim
    fi
else
    echo "==> WARN: 'nvim' not avialable, not creating a symlink."
fi

# link kitty config only when kitty available
if command -v kitty &> /dev/null
then
    kitty_link=$(readlink -f ${HOME}/.config/kitty)
    if [ "$kitty_link" = "${PWD}/.config/kitty" ]; then
    	echo "==> kitty config link to ~/.config/kitty already exists"
    else
    	echo "==> linking  kitty config to ~/.config/kitty"
        ln -s ${PWD}/.config/kitty ${HOME}/.config/kitty
    fi
else
    echo "==> WARN: 'kitty' not avialable, not creating a symlink."
fi
