#!/bin/sh

cd "$(dirname "$0")"
cd ../

unlink ${HOME}/.config/nvim &> /dev/null
ln -s ${PWD}/.config/nvim ${HOME}/.config/nvim
unlink ${HOME}/.config/kitty &> /dev/null
ln -s ${PWD}/.config/kitty ${HOME}/.config/kitty

