name: Send submodule updates to parent repo

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: lpoto/.dotfiles
          submodules: true
          token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}

      - name: Pull & update nvim submodule recursively
        run: |
          git submodule update --init nvim
          git submodule update --remote nvim
      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add --all
          git commit -m "Update nvim submodule" || echo "No changes to commit"
          git push
